### ISSUE TITLE
starling Image rotation

### ISSUE THREAD

**Issue by vizgl** [mindjolt/starling-builder-editor#3] opened 2015-11-12 23:43 UTC
I have image with different from default width or height(scaleX or scaleY). Then, when I change rotation, image size returns to default values.

**Comment by ghost** [comment] 2015-11-13 21:40
Thanks for the report.
The issue is caused by a race condition between width/height and rotation.
I have a fix to disable setting width/height when rotation is not 0.
https://github.com/mindjolt/starling-builder-editor/commit/130abfea12a9bade448941f6bd9d3eabf4419b84
It's not ideal, but it should fix your problem.
So make sure to set width/height/scale first before you do rotation.

**Comment by ghost** [comment] 2015-11-17 19:58
Pushed the fixed to 0.6.1.

**Closed as completed by ghost** 2015-11-17 19:58 UTC
