### ISSUE TITLE
wrong Image scaleX/scaleY, when rotated

### ISSUE THREAD

**Issue by vizgl** [mindjolt/starling-builder-editor#4] opened 2015-11-19 12:17 UTC
When I rotate image, it got wrong size values. Values based on bounding box of the image, but need to be based on real image size.

Rotate image, with scaleX: 1, scaleY: 1, by 45 degrees. Now, image has scaleX: 1.5, scaleY: 1.5. This wrong values will be written in the layout file. But real values should be scaleX: 1, scaleY: 1.

**Comment by yuhengh** [comment] 2015-11-19 19:29
Thanks for the report. I saw the issue now. Basically when a display object is created it's trying to set width, height, scaleX, scaleY, rotation in the following order. The problem is scaleX/scaleY will not be saved when it's default to 1, which causing the issue. 

To be able to fix it, you can go to menu Workspace -> Edit template override, and then remove the default_value for scaleX/scaleY and reload the editor. The only downside is scaleX/scaleY will save to the layout even if it's default to 1. It won't break anything, just saving some extra information more than needed.

The best fix is not to save width/height/scaleX/scaleY in this case. 
I will come up with some custom rules for saving property in future version.

**Comment by ghost** [comment] 2015-12-05 01:01
This issue is fixed in the latest v0.6.2. Width/height are marked as read-only and won't save to layout files

**Closed as completed by ghost** 2015-12-05 01:01 UTC
